# -*- coding: utf-8 -*-
"""PLS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qxW-dIoMTWrRjQF6i1t--Ib-8JdfymaI

#https://colab.research.google.com/drive/1qxW-dIoMTWrRjQF6i1t--Ib-8JdfymaI?usp=sharing
"""

import numpy as np
np.set_printoptions(precision=2)

def plsr_nipalsm(X, Y, A):
    X = np.asarray(X, dtype=float)
    Y = np.asarray(Y, dtype=float)

    n, p = X.shape
    _, m = Y.shape  # ignored number of rows

    # Step 1: Do NOT center the data
    X0 = (X - 0 * np.mean(X, axis=0)) / 1.0
    Y0 = (Y - 0 * np.mean(Y, axis=0)) / 1.0

    # Pre-allocate matrices for storage
    T = np.zeros((n, A))
    P = np.zeros((p, A))
    W = np.zeros((p, A))
    Q = np.zeros((m, A))
    U = np.zeros((n, A))
    B = np.zeros((A, A))

    max_iter = 500
    tolerance = 1e-6

    # Step 2: Iterative Loop for Each Component
    for h in range(A):
        # 2.1 Initialize Y-score u with a column of Y0
        u = Y0[:, 0].copy()

        u_old = np.zeros(n)

        for _iter in range(max_iter):
            # 2.2 Compute and normalize X-weights (w)
            w = (X0.T @ u) / (u.T @ u)  # X0 is same as E0

            w = w / np.linalg.norm(w)

            # 2.3 Compute X-scores (t)
            t = (X0 @ w) / (w.T @ w)

            # 2.4 Compute Y-weights/loadings (q)
            q = (Y0.T @ t) / (t.T @ t)

            q = q / np.linalg.norm(q)

            # 2.5 Update Y-scores (u) Most Important Step
            u = (Y0 @ q) / (q.T @ q)

            # 2.6 Check for convergence of the score vector
            if np.linalg.norm(u - u_old) < tolerance:
                break
            u_old = u.copy()

        # 2.7 Compute X-loadings (p)
        p_vec = (X0.T @ t) / (t.T @ t)
        t = t * np.linalg.norm(p_vec)
        pprime = p_vec.T / np.linalg.norm(p_vec)
        p_vec = pprime.T

        # Store the results for component h
        T[:, h] = t
        P[:, h] = p_vec
        W[:, h] = w
        Q[:, h] = q
        U[:, h] = u
        b = (t.T @ u) / (t.T @ t)

        B[h, h] = b

        # 2.8 Deflate X0 and Y0 matrices
        X0 = X0 - np.outer(t, p_vec)

        Y0 = Y0 - b * np.outer(t, q)  # Using inner relation: Y0 = Y0 - b*t*q' (where b=1 for normalized t)

    # Step 3: Compute final regression coefficients (Beta)
    # Transform weights to be compatible with original un-deflated X
    W_star = W @ np.linalg.inv(P.T @ W)
    Beta = W_star @ B @ Q.T

    return Beta, T, P, W, Q, U, B

import numpy as np

#from plsr_nipalsm import plsr_nipalsm

# %% 1. X and Y Data

n = 5  # Number of samples
p = 6  # Number of predictors

n = 10  # Number of samples
p = 5  # Number of predictors

X = np.array([
    [-1.037, 0.604, -1.561, -2.472, 1.297],
    [2.145, 0.513, 0.396, 2.527, -2.35],
    [1.021, 0.134, 0.55, 1.697, -1.417],
    [0.442, 0.889, -1.431, -1.024, -0.233],
    [-1.599, -0.758, -0.519, -1.783, 1.869],
    [-1.604, -0.485, -0.359, -2.028, 1.648],
    [-1.993, -0.864, 0.407, -1.656, 2.051],
    [1.427, 1.021, -0.698, 0.703, -1.355],
    [0.224, 0.413, -0.438, -0.032, -0.395],
    [0.637, 0.917, -1.43, -0.547, -0.378],
])

Y = np.array([
    [0.305, -2.018, -0.745],
    [0.774, 2.835, 0.096],
    [0.298, 2.028, -0.245],
    [0.939, -0.94, -1.011],
    [-0.715, -2.259, 0.167],
    [-0.678, -1.733, 0.126],
    [-1.399, -1.742, 0.905],
    [1.328, 0.752, -0.889],
    [0.487, 0.075, -0.552],
    [1.034, -0.478, -1.303],
])

# %% 2. Run PLSR NIPALS Algorithm
num_components = 3  # Extracting 3 latent variables
Beta, T, P, W, Q, U, B = plsr_nipalsm(X, Y, num_components)

XPRED = T @ P.T
YPRED = T @ B @ Q.T
# Beta = W_star * b * Q'

# Beta_W = W @ np.linalg.inv(W.T @ W) @ B @ Q.T
Beta_P = W @ np.linalg.inv(P.T @ W) @ B @ Q.T

# Betas = [Beta_W, Beta_P]

# YPRED_W = X @ Beta_W
YPRED_P = X @ Beta_P

# YPREDs = [YPRED_W, YPRED_P]

# Predict new observations using the PLSR model
# YPRED_NEWW = XNEW @ Beta_W  # Using Beta_W for predictions
# YPRED_NEWP = XNEW @ Beta_P  # Using Beta_W for predictions

# YPRED_NEW = [YPRED_NEWW, YPRED_NEWP]

# PRESS calculations

# Leave-one-out PRESS for PLS2
# ---------------------------------------------------

n = X.shape[0]
q = Y.shape[1]

YPRED = np.zeros(Y.shape)
TotalResid = 0
ResidSq = 0

for i in range(n):

    idx = np.ones(n, dtype=bool)
    idx[i] = False

    Xtrain = X[idx, :]
    Ytrain = Y[idx, :]

    Beta_Train, Tnew, Pnew, Wnew, Qnew, Unew, Bnew = plsr_nipalsm(Xtrain, Ytrain, num_components)

    YPRED[i, :] = X[i, :] @ Beta_Train

for j in range(q):
    ResidSq = ResidSq + (Y[:, j] - YPRED[:, j]).T @ (Y[:, j] - YPRED[:, j])

PRESS = ResidSq
RMSECV = np.sqrt(PRESS / ((n - 1) * q))

# PRESS = sum(Residual(:).^2)
# RMSECV = sqrt(PRESS/(n*q))

if __name__ == "__main__":
    np.set_printoptions(precision=2, suppress=True)
    print("Beta:\n", Beta)
    print("\nB (diagonal):\n", B)
    print(f"\nPRESS: {PRESS:.2f}",)
    print(f"RMSECV: {RMSECV:.2f}", )

